apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-svc
  namespace: {{ .Values.global.namespace }}
  labels:
    app: finops-frontend
spec:
  selector:
    app: finops-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
      name: http
  type: ClusterIP
