{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finops-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          # API → backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.name }}-svc
                port:
                  number: 8000
          # Health → backend
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.name }}-svc
                port:
                  number: 8000
          # Everything else → frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.name }}-svc
                port:
                  number: 80
{{- end }}
